# Generated by Django 4.2.11 on 2025-04-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_alter_firefighters_rank_alter_firefighters_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fire.firestation'),
        ),
    ]
