# Generated by Django 4.2.11 on 2025-04-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_alter_firefighters_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='fire.firestation'),
            preserve_default=False,
        ),
    ]
